baseURL = "https://ksajan.github.io/"
languageCode = "en-us"
title = "Sajan Kumar"
theme = "sans"
publishDir = "public"

canonifyURLs = false
relativeURLs = false

enableRobotsTXT = true
summaryLength = 50
defaultMarkdownHandler = "goldmark"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.146.0"

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\\[', '\\]'], ['$$', '$$']]
          inline = [['\\(', '\\)']]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS", "JSON"]
  taxonomy = ["HTML", "RSS"]

[permalinks]
  posts = "/blog/:year/:month/:slug/"
  projects = "/projects/:slug/"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
