  [[main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

  [[main]]
    name = 'Categories'
    pageRef = '/categories'
    weight = 40

   [[main]]
    name = 'About'
    pageRef ='/pages/about/'
    weight = 50 

  [[main]]
    name='Docs'
    identifier='guides'
    url='/doc/'
    weight=70
       params = {target = "_blank" }
 [[main]]
      parent = "guides"
      name = "Nested Link 1"
      url = "/docs/guides/beginner/"
      weight = 71

      [[main]]
      parent = "guides"
      name = "Nested Link 2"
      url = "/docs/guides/advanced/"
      weight = 72